.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH YT-UPLOAD-LOGIN 1 2026-09-13 "yt-upload 0.2.0" "General Commands Manual"
.SH NAME
yt\-upload\-login \- Authorize this CLI with a Google account
.SH SYNOPSIS
\fByt\-upload login\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Authorize this CLI with a Google account
.SH OPTIONS
.TP
\fB\-\-force\fR
Re\-run the browser consent flow even if already logged in
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
