.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH YT-UPLOAD-LOGOUT 1 2026-09-13 "yt-upload 0.2.0" "General Commands Manual"
.SH NAME
yt\-upload\-logout \- Forget the cached credentials
.SH SYNOPSIS
\fByt\-upload logout\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Forget the cached credentials
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
