.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH yt-upload-status 1  "status " 
.SH NAME
yt\-upload\-status \- Show whether yt\-upload is currently authorized
.SH SYNOPSIS
\fByt\-upload status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show whether yt\-upload is currently authorized
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
